apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: gru.ocir.io/grzmxlhavk8p/joyce.passos@zup.com.br/oracle-oci-testes/dockerteste:latest
          ports:
            - containerPort: 5000
