apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/crossplane/crossplane/master/config/crds.yaml
  - https://raw.githubusercontent.com/crossplane/crossplane/master/config/default.yaml