-- Criação da tabela de pesquisas
CREATE TABLE polls (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    question VARCHAR2(255) NOT NULL,
    PRIMARY KEY (id)
);

-- Criação da tabela de opções de resposta
CREATE TABLE poll_options (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    poll_id NUMBER NOT NULL,
    option_text VARCHAR2(255) NOT NULL,
    votes NUMBER DEFAULT 0,
    PRIMARY KEY (id),
    FOREIGN KEY (poll_id) REFERENCES polls(id) ON DELETE CASCADE
);
