apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey-app
  template:
    metadata:
      labels:
        app: survey-app
    spec:
      containers:
      - name: survey-app
        image: gru.ocir.io/grzmxlhavk8p/oracle-oci-testes/my-survey-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_host
