apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-survey-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-survey-app
  template:
    metadata:
      labels:
        app: my-survey-app
    spec:
      containers:
      - name: my-survey-app
        image: gru.ocir.io/grzmxlhavk8p/oracle-oci-testes/my-survey-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://username:password@host:5432/dbname"
        - name: FLASK_APP
          value: "app.py"
        - name: FLASK_ENV
          value: "production"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0