name: Deploy OCI Resources with Crossplane

on:
  push:
    branches: 
       - feat/crossplane
  workflow_dispatch:

jobs:
  install:
    name: Install CrossPlane
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_USER_OCID }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Clone Crossplane repository
      run: |
        git clone https://github.com/crossplane/crossplane.git
        cd crossplane
        go get -u github.com/crossplane/crossplane/cmd/crossplane
        go get -u github.com/crossplane/crossplane/cmd/kubectl-crossplane

    - name: Generate CRDs
      run: |
        make generate

    - name: Apply CRDs
      run: |
        kubectl apply -f install.yaml

    - name: Configure Kubectl
      uses: oracle-actions/configure-kubectl-oke@v1.5.0
      with:
        cluster: ${{ secrets.OKE_CLUSTER_OCID }}

    - name: Create oci-creds secret
      run: |
        bash -e create-secret.sh

    - name: Apply provider config
      run: |
        kubectl apply -f examples/providerconfig/secret.yaml
        kubectl apply -f examples/providerconfig/providerconfig.yaml

  deploy:
    needs: install
    name: Apply Object Storage Bucket Configuration 
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_USER_OCID }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_REGION }}
      OCI_REGION: ${{ secrets.OCI_REGION }}.ocir.io

    steps:
    - name: Configure Kubectl
      uses: oracle-actions/configure-kubectl-oke@v1.5.0
      with:
        cluster: ${{ secrets.OKE_CLUSTER_OCID }}

    - name: Checkout
      uses: actions/checkout@v4.1.7
            
    - name: Deploy to Kubernetes
      run: |        
        envsubst < examples/objectstorage/bucket.yaml | kubectl apply -f -