name: Deploy Kubernetes
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.6.1
      
    - name: Login to Oracle Cloud Infrastructure Registry (OCIR)
      run: |
        echo "${{ secrets.OCI_AUTH_TOKEN }}" | docker login -u "${{ secrets.OCI_NAMESPACE }}/${{ secrets.OCI_USER_MAIL }}" ${{ secrets.OCI_REGION }}.ocir.io --password-stdin        
        
    - name: Build and push Docker image to OCI
      run: |
        cd my-survey-app
        docker build -t ${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCI_NAMESPACE }}/${{ secrets.NAME_REPO }}/my-survey-app:latest .
        docker push ${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCI_NAMESPACE }}/${{ secrets.NAME_REPO }}/my-survey-app:latest      

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/v1.26.3/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Install OCI CLI
      run: |
        curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash

    - name: Configure OCI CLI
      run: |
        oci setup config --config-file $HOME/.oci/config --profile DEFAULT

    - name: Configure kubectl with OCI CLI
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        cd my-survey-app
        kubectl get nodes
        kubectl apply -f deployment.yaml --request-timeout='2m'
        kubectl get pods
        kubectl apply -f service.yaml --request-timeout='2m'
        kubectl get service
