name: Deploy OCI Resources with Crossplane

on:
  push:
    branches: 
       - feat/crossplane
  workflow_dispatch:

jobs:
  install:
    name: Install CrossPlane
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_USER_OCID }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:
    - name: Configure Kubectl
      uses: oracle-actions/configure-kubectl-oke@v1.5.0
      with:
        cluster: ${{ secrets.OKE_CLUSTER_OCID }}

    - name: Checkout code
      uses: actions/checkout@v4.1.7
      

    - name: Adicione um repositório Helm para Crossplane.
      run: helm repo add crossplane-stable https://charts.crossplane.io/stable

    - name: Atualize o repositório Helm
      run: helm repo update

    - name: Install Crossplane via Helm
      run: helm upgrade crossplane --namespace crossplane-system crossplane-stable/crossplane --create-namespace
     #  run: helm install my-crossplane --namespace crossplane-system crossplane-stable/crossplane --create-namespace - se não tivesse um criado

    - name: Configure OCI Provider
      run: |
        kubectl apply -f examples/providerconfig/secret.yaml
        kubectl apply -f examples/providerconfig/providerconfig.yaml
        kubectl create secret generic oci-creds -n crossplane-system \
          --from-literal=user_ocid=${OCI_CLI_USER} \
          --from-literal=tenancy_ocid=${OCI_CLI_TENANCY} \
          --from-literal=fingerprint=${OCI_CLI_FINGERPRINT} \
          --from-literal=private_key=${OCI_CLI_KEY_CONTENT} \
          --from-literal=region=${OCI_CLI_REGION}

  deploy:
    needs: install
    name: Apply Object Storage Bucket Configuration 
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_USER_OCID }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OCI_REGION: ${{ secrets.OCI_REGION }}.ocir.io

    steps:
    - name: Configure Kubectl
      uses: oracle-actions/configure-kubectl-oke@v1.5.0
      with:
        cluster: ${{ secrets.OKE_CLUSTER_OCID }}
        
    - name: Checkout
      uses: actions/checkout@v4.1.7
            
    - name: Deploy to Kubernetes
      run: |        
        envsubst < examples/objectstorage/bucket.yaml | kubectl apply -f -
