name: Deploy Kubernetes

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.6.1
      
    - name: Login to Oracle Cloud Infrastructure Registry (OCIR)
      run: |
        echo "${{ secrets.OCI_AUTH_TOKEN }}" | docker login -u "${{ secrets.OCI_NAMESPACE }}/${{ secrets.OCI_USER_MAIL }}" ${{ secrets.OCI_REGION }}.ocir.io --password-stdin        
        
    - name: Build and push Docker image to OCI
      run: |
        cd my-survey-app
        docker build -t ${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCI_NAMESPACE }}/${{ secrets.NAME_REPO }}/my-survey-app:latest .
        docker push ${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCI_NAMESPACE }}/${{ secrets.NAME_REPO }}/my-survey-app:latest  

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_USER_OCID }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:
    - name: Configure Kubectl
      uses: oracle-actions/configure-kubectl-oke@v1.5.0
      with:
        cluster: ocid1.cluster.oc1.sa-saopaulo-1.aaaaaaaa2mbcxhg6mcvpallift6hxf5jxnm26564hbx3xp6x3c6a74hpmjsa
        
    - name: Checkout
      uses: actions/checkout@v4
            
    - name: Deploy to Kubernetes
      run: |
       envsubst < my-survey-app/deployment.yaml | kubectl apply -f - -n ${{ env.OCI_NAMESPACE }}
       envsubst < my-survey-app/service.yaml | kubectl apply -f  - -n ${{ env.OCI_NAMESPACE }}
