name: Deploy Kubernetes Helm

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.6.1
    - name: Login to Oracle Cloud Infrastructure Registry (OCIR)
      run: |
        echo "${{ secrets.OCI_AUTH_TOKEN }}" | docker login -u "${{ secrets.OCI_NAMESPACE }}/${{ secrets.OCI_USER_MAIL }}" ${{ secrets.OCI_REGION }}.ocir.io --password-stdin        
    - name: Build and push Docker image to OCI
      run: |
        cd my-survey-app
        docker build -t ${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCI_NAMESPACE }}/${{ secrets.NAME_REPO }}/my-survey-app:latest .
        docker push ${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCI_NAMESPACE }}/${{ secrets.NAME_REPO }}/my-survey-app:latest      
    - name: Upload chart 
      uses: actions/upload-artifact@v4.3.5
      with:
        name: app-chart-${{ github.sha }}
        path: chart/
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download chart
        uses: actions/download-artifact@v4.1.8
        with:
          name: app-chart-${{ github.sha }}
          path: chart/
      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.5.0
        id: kubectl-oke-action
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}      
      - name: Deploy to Kubernetes
      run: |
        cd my-survey-app
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
