name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to OCI Container Registry
      env:
        OCI_CLI_AUTH: instance_principal
        OCI_USER_OCID: ${{ secrets.OCI_USER_OCID }}
        OCI_TENANCY_OCID: ${{ secrets.OCI_TENANCY_OCID }}
        OCI_COMPARTMENT_OCID: ${{ secrets.OCI_COMPARTMENT_OCID }}
        OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
      run: |
        echo "${{ secrets.OCI_AUTH_TOKEN }}" | docker login ${{ secrets.OCI_REGION }} --username=${{ secrets.OCI_USER_OCID }} --password-stdin

    - name: Build and push Docker image to OCI
      run: |
        docker build . -t ${{ secrets.OCI_REPO }}:latest
        docker push ${{ secrets.OCI_REPO }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
