name: Deploy to Kubernetes

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
          
    - name: Login to OCI Container Registry
      uses: oracle-actions/login-ocir@v1.3.0
      with:  
        auth_token: ${{ secrets.OCI_AUTH_TOKEN }} 
        region: gru.ocir.io


    - name: Build and push Docker image to OCI
      run: |
        docker build . -t ${{ secrets.OCI_REPO }}:latest
        docker push ${{ secrets.OCI_REPO }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
